# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b5596ad5f9d967db49c2d2842dc13837e3b5e1de572f88e9e1d8edaf0ca18e3bd1e908b74c7f1d6fc7120a6deaeeda5bbcf8e1abec020d331560f4e3c0101ab

test:
  secret_key_base: 15537dd4d6e8458f7788fcac20f2dc609bcfdb1cab699052f66d068e9ccb4c24b34a8b3786a6e74ff481c551c0d155cc18af242bd9ec3159218ac6f4cb2c2e50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
